export const brazilianStates = [
  { uf: "AC", name: "Acre" },
  { uf: "AL", name: "Alagoas" },
  { uf: "AP", name: "Amapá" },
  { uf: "AM", name: "Amazonas" },
  { uf: "BA", name: "Bahia" },
  { uf: "CE", name: "Ceará" },
  { uf: "DF", name: "Distrito Federal" },
  { uf: "ES", name: "Espírito Santo" },
  { uf: "GO", name: "Goiás" },
  { uf: "MA", name: "Maranhão" },
  { uf: "MT", name: "Mato Grosso" },
  { uf: "MS", name: "Mato Grosso do Sul" },
  { uf: "MG", name: "Minas Gerais" },
  { uf: "PA", name: "Pará" },
  { uf: "PB", name: "Paraíba" },
  { uf: "PR", name: "Paraná" },
  { uf: "PE", name: "Pernambuco" },
  { uf: "PI", name: "Piauí" },
  { uf: "RJ", name: "Rio de Janeiro" },
  { uf: "RN", name: "Rio Grande do Norte" },
  { uf: "RS", name: "Rio Grande do Sul" },
  { uf: "RO", name: "Rondônia" },
  { uf: "RR", name: "Roraima" },
  { uf: "SC", name: "Santa Catarina" },
  { uf: "SP", name: "São Paulo" },
  { uf: "SE", name: "Sergipe" },
  { uf: "TO", name: "Tocantins" },
];

export const brazilianCities: { [uf: string]: string[] } = {
  "BA": ["Luís Eduardo Magalhães", "Salvador", "Feira de Santana", "Vitória da Conquista", "Barreiras", "Camaçari", "Itabuna", "Ilhéus"],
  "SP": ["São Paulo", "Campinas", "Guarulhos", "Santos", "Ribeirão Preto"],
  "RJ": ["Rio de Janeiro", "Niterói", "Duque de Caxias", "São Gonçalo"],
  "MG": ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora"],
  "PE": ["Recife", "Jaboatão dos Guararapes", "Olinda"],
  "CE": ["Fortaleza", "Caucaia", "Juazeiro do Norte"],
  "PR": ["Curitiba", "Londrina", "Maringá"],
  "RS": ["Porto Alegre", "Caxias do Sul", "Pelotas"],
  "GO": ["Goiânia", "Aparecida de Goiânia", "Anápolis"],
  "AM": ["Manaus", "Parintins"],
  "PA": ["Belém", "Ananindeua"],
  "SC": ["Florianópolis", "Joinville", "Blumenau"],
  "DF": ["Brasília"],
  "ES": ["Vitória", "Vila Velha", "Serra"],
  "MA": ["São Luís", "Imperatriz"],
  "MS": ["Campo Grande", "Dourados"],
  "MT": ["Cuiabá", "Várzea Grande"],
  "PB": ["João Pessoa", "Campina Grande"],
  "PI": ["Teresina", "Parnaíba"],
  "RN": ["Natal", "Mossoró"],
  "RO": ["Porto Velho", "Ji-Paraná"],
  "RR": ["Boa Vista"],
  "SE": ["Aracaju", "Nossa Senhora do Socorro"],
  "TO": ["Palmas", "Araguaína"],
  "AC": ["Rio Branco"],
  "AL": ["Maceió", "Arapiraca"],
  "AP": ["Macapá"],
};